from api.github_helper.utils import get_text_from_html_url
from api.github_helper.installation import get_installation_access_token
from codecheck.actions.reviews import review_pull_request
import requests
import logging

logger = logging.getLogger(__name__)


def process_pull_request(payload):
    comment_url = payload["pull_request"]["comments_url"]
    diff_url = payload["pull_request"]["diff_url"]
    installation_id = payload["installation"]["id"]
    pl_title = payload["pull_request"]["title"]
    pl_description = payload["pull_request"]["body"]

    access_token = get_installation_access_token(installation_id)
    diff_text = get_text_from_html_url(diff_url, access_token)
    review_body = review_pull_request(
        diff_text=diff_text,
        pull_request_title=pl_title,
        pull_request_desc=pl_description,
    )
    post_pull_request(comment_url, review_body, access_token)


def post_pull_request(url, data, access_token):
    data = {"body": f"{data}\n\n -- Generated by Cloud Code AI"}
    headers = {
        "Authorization": f"Bearer {access_token}",
        "Accept": "application/vnd.github.v3+json",
    }
    response = requests.post(url, headers=headers, json=data)
    logger.info(f"Post Pull request response: {response.text}")
