import logging

logger = logging.getLogger(__name__)


PR_COLLAPSIBLE_TEMPLATE = """
<details>
<summary>{comment}</summary>

### Reason
{reasoning}

### Confidence
{confidence}
</details>
"""

DESC_COLLAPSIBLE_TEMPLATE = """
<details>
<summary>Original Description</summary>

{desc}

</details>
"""


def create_pr_review_from_json(data):
    markdown_output = "## Code Review Feedback\n\n"

    for review in data["review"]:
        markdown_output += f"### {review['topic']}\n\n"
        ct = PR_COLLAPSIBLE_TEMPLATE.format(
            comment=review.get("comment", "NA"),
            reasoning=review.get("reasoning", "NA"),
            confidence=review.get("confidence", "NA"),
        )
        markdown_output += ct + "\n"

    return markdown_output


def create_pr_description(data, original_desc):
    markdown_output = "## Autogenerated PR Description"
    markdown_output += data["desc"]
    markdown_output += "\n\n -- Generated with love by Cloud Code AI"
    markdown_output += "\n\n" + DESC_COLLAPSIBLE_TEMPLATE.format(desc=original_desc)
    return markdown_output
