from helpers import output, parser
import requests

def review_pull_request(
        comment_url: str,
        diff_text: str,
        access_token: str,

):

    # tips = r2r_client.filtered_search("What are some tips to remember while doing code review?", 5, {"tags": "tips"})
    # tips_to_text = "\n-->".join([t['metadata']['text'] for t in tips])

    prompt = prompts.REVIEW_CODE.format(
        context=payload["pull_request"]["body"],
        inst = tips_to_text,
        code = 
    )
    print("Outgoing Prompt:", prompt)
    resp = generate_llm_resp(prompt)

    body = output.json_to_markdown(parser.extract_json(resp))
    data = {
        "body": f"## Here is my AI generated review.\n {body}\n\n -- Generated by Cloud Panda"
    }
    headers = {
        'Authorization': f'Bearer {access_token}',
        'Accept': 'application/vnd.github.v3+json'
    }
    response = requests.post(comment_url, headers=headers, json=data)
